# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import treinamento_pb2 as treinamento__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in treinamento_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModeloServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fit = channel.unary_unary(
                '/lab1.ModeloService/Fit',
                request_serializer=treinamento__pb2.FitRequest.SerializeToString,
                response_deserializer=treinamento__pb2.FitResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/lab1.ModeloService/Predict',
                request_serializer=treinamento__pb2.PredictRequest.SerializeToString,
                response_deserializer=treinamento__pb2.PredictResponse.FromString,
                _registered_method=True)


class ModeloServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Fit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModeloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fit': grpc.unary_unary_rpc_method_handler(
                    servicer.Fit,
                    request_deserializer=treinamento__pb2.FitRequest.FromString,
                    response_serializer=treinamento__pb2.FitResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=treinamento__pb2.PredictRequest.FromString,
                    response_serializer=treinamento__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab1.ModeloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lab1.ModeloService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModeloService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Fit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab1.ModeloService/Fit',
            treinamento__pb2.FitRequest.SerializeToString,
            treinamento__pb2.FitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab1.ModeloService/Predict',
            treinamento__pb2.PredictRequest.SerializeToString,
            treinamento__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
