# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: treinamento.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'treinamento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11treinamento.proto\x12\x04lab1\",\n\x07\x41mostra\x12\x11\n\tatributos\x18\x01 \x03(\x02\x12\x0e\n\x06rotulo\x18\x02 \x01(\x05\"1\n\nFitRequest\x12#\n\x0c\x64\x61\x64os_treino\x18\x01 \x03(\x0b\x32\r.lab1.Amostra\"\x1f\n\x0b\x46itResponse\x12\x10\n\x08\x61\x63uracia\x18\x01 \x01(\x02\"#\n\x0ePredictRequest\x12\x11\n\tatributos\x18\x01 \x03(\x02\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32s\n\rModeloService\x12*\n\x03\x46it\x12\x10.lab1.FitRequest\x1a\x11.lab1.FitResponse\x12\x36\n\x07Predict\x12\x14.lab1.PredictRequest\x1a\x15.lab1.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'treinamento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AMOSTRA']._serialized_start=27
  _globals['_AMOSTRA']._serialized_end=71
  _globals['_FITREQUEST']._serialized_start=73
  _globals['_FITREQUEST']._serialized_end=122
  _globals['_FITRESPONSE']._serialized_start=124
  _globals['_FITRESPONSE']._serialized_end=155
  _globals['_PREDICTREQUEST']._serialized_start=157
  _globals['_PREDICTREQUEST']._serialized_end=192
  _globals['_PREDICTRESPONSE']._serialized_start=194
  _globals['_PREDICTRESPONSE']._serialized_end=227
  _globals['_MODELOSERVICE']._serialized_start=229
  _globals['_MODELOSERVICE']._serialized_end=344
# @@protoc_insertion_point(module_scope)
